version: "3.1"

services:
  rng:
    image: dennisn84/rpi-dockercoins_rng:1.0
    networks:
    - dockercoins
    ports:
    - "8001:80"
    deploy:
      mode: global

  hasher:
    image: dennisn84/rpi-dockercoins_hasher:1.0
    networks:
    - dockercoins
    ports:
    - "8002:80"

  webui:
    image: dennisn84/rpi-dockercoins_webui:1.0
    networks:
    - dockercoins
    ports:
    - "8000:80"

  redis:
    image: redis
    networks:
    - dockercoins
    deploy:
      placement:
        constraint:
          - node.role == manager

  worker:
    image: dennisn84/rpi-dockercoins_worker:1.0
    networks:
    - dockercoins
    deploy:
      replicas: 6
      update_config:
        parallelism: 3
        # delay: 5s
      placement:
        constraint:
          - node.role == worker

networks:
    dockercoins:
